name: Build switch-library-manager

# On master and manually
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Setup astilectron
        run: |
          go get -u github.com/asticode/go-astilectron-bundler/...
          go install github.com/asticode/go-astilectron-bundler/astilectron-bundler

      - name: Bundle
        run: ~/go/bin/astilectron-bundler

      - name: Zip the MacOS release
        run: |
          cd output/darwin-amd64
          zip -q -X -r Switch-Library-Manager-${RELEASE_VERSION}-MacOS.zip Switch-Library-Manager.app/
          cd ../..

      - name: Zip the Linux release
        run: |
          cd output/linux-amd64
          zip -q -X Switch-Library-Manager-${RELEASE_VERSION}-Linux.zip Switch-Library-Manager
          cd ../..

      - name: Zip the Windows release
        run: |
          cd output/windows-amd64
          zip -q -X Switch-Library-Manager-${RELEASE_VERSION}-Windows.zip Switch-Library-Manager.exe
          cd ../..

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true